### ISSUE TITLE
revisit efficiency of serialization of tensors of std::complex

### ISSUE THREAD

**Issue by evaleev** [BTAS/BTAS#73]
see @shiozaki comment: https://github.com/BTAS/BTAS/commit/17ea3375c02d08db7352860f025d387676252a7b#commitcomment-9230781

**Comment by evaleev** [comment]
@shiozaki which version of boost do you use? It seems that the native serialization of std::array was introduced only in 1.56 and it does not play along with the optimizations in issue #40 ...

**Comment by shiozaki** [comment]
it was based on 1.54 or something like that. std::array is irrelevant to boost::serialization::make_array used in varray.h. But I saw that actually varray.h is calling btas::make_array, so it is fine (see btas/serialization.h).

Looking at boost/serialization/complex.hpp it may be fine by now (but I do not know).

**Comment by shiozaki** [comment]
so I guess this issue can be closed
