### ISSUE TITLE
serialization error: BoxOrdinal

### ISSUE THREAD

**Issue by shiozaki** [BTAS/BTAS#78]
My student Ryan (@RDReynolds) has found an issue - see below. @evaleev do you have any idea?

>Toru,
>
>I have traced back the problem with the Reference serialization test case.  (hf_tzvpp_bfgs_saveref.json)  An assert statement in boost::serialization indicated that we were trying to save a bool that was never instantiated, and gdb pointed to line 211 of btas/ordinal.h as the culprit.  It seems the problem does not occur if we change line 39 of btas/ordinal.h to the following:
>
>BoxOrdinal() { contiguous_ = true; }
>
>Probably the appropriate solution instead deals with where this constructor is called, though.
>
>Best,
>Ryan
>
> PS: Note that because it's an assert statement, boost only picks up the error in debug mode. That's why it ran without problems for me originally.

**Comment by evaleev** [comment]
@RDReynolds do I understand correctly that the compiler seems to *optimize out* the class member contiguous_ ? that in principle should not be possible since it is used by serialization ... could you provide extra details here? Error message and the compiler+boost version you used at least.

**Comment by shiozaki** [comment]
I don't think this is optimization. The error was observed with -O0 -g. gcc 4.8.3 and boost 1.55.

If I understood this is because in some context BoxOrdinal is constructed in a way that a member is not initialized (i.e., default constructor is called), and boost does not allow that to be serialized.

**Comment by shiozaki** [comment]
error message
```
lt-TestSuite: /usr/local/include/boost/archive/basic_binary_iprimitive.hpp:98: void boost::archive::basic_binary_iprimitive<Archive, Elem, Tr>::load(bool&) [with Archive = boost::archive::binary_iarchive; Elem = char; Tr = std::char_traits<char>]: Assertion `0 == i || 1 == i' failed.
```

**Comment by shiozaki** [comment]
FYI: this comes from the following line when loading from an archive, which basically states that the stored boolean was not initialized. 
```
basic_binary_iprimitive.hpp
    void load(bool & t){
        load_binary(& t, sizeof(t));
        int i = t;
        BOOST_ASSERT(0 == i || 1 == i);
        (void)i; // warning suppression for release builds.
    }
```

**Comment by evaleev** [comment]
OK, I suspected that "instantiated" in the issue statement meant
"initialized". The standard does not allow to avoid "instantiating" unused
members, so that did not make much sense.

This is annoying  but for a debug build the penalty matters little ... I
will avoid doing this for a release build.

On Sat, May 2, 2015 at 7:20 AM, Toru Shiozaki <notifications@github.com>
wrote:

> FYI: this comes from the following line when loading from an archive,
> which basically states that the stored boolean was not initialized.
>
> basic_binary_iprimitive.hpp
>     void load(bool & t){
>         load_binary(& t, sizeof(t));
>         int i = t;
>         BOOST_ASSERT(0 == i || 1 == i);
>         (void)i; // warning suppression for release builds.
>     }
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/BTAS/BTAS/issues/78#issuecomment-98348127>.
>



-- 
web: valeyev.net

**Comment by shiozaki** [comment]
Ah ok I did not catch that. To clarify - are you going to fix this by putting in this initialization in ifndef NDEBUG block or something? (well I am fine with any resolution as long as the code works!)

**Comment by evaleev** [comment]
I pushed a change, please try.

**Comment by shiozaki** [comment]
Yes it runs through now. Thanks!
