### ISSUE TITLE
where is the make files

### ISSUE THREAD

**Issue by shiyangdaisy** [BTAS/BTAS#79]
I tried to run the test cases in the folder, but I don't know how to make files first so that libraries can be included when compiling.

Thanks!

**Comment by justusc** [comment]
You need to run CMake to generate the make files. Also, BTAS is a header only library, so there is nothing to compile. Once you generate the make files, you can immediately run ```make check```

**Comment by shiyangdaisy** [comment]
Thanks!
I got an error when doing cmake :
CMake Error at CMakeLists.txt:98 (message):
  Compiler cannot compile C++11 code with -std=c++11 or -std=c++0x flags;
  provide the appropriate command-line flags explicitly via
  -DCMAKE_CXX_FLAGS="" or try a newer compiler

I have gcc 4.4.7 on centos 6, I can not update gcc so I was trying to specify -DCMAKE_CXX_FLAG while running cmake for c++ compatibility. How could I specify this, ie, what is the command line syntax that I should use with cmake?

**Comment by evaleev** [comment]
@shiyangdaisy BTAS requires a C++ compiler with C++11 support. Your compiler is too old. For the particular case of gcc, you need at least gcc 4.7 .
