### ISSUE TITLE
implementation of gemm etc

### ISSUE THREAD

**Issue by shiozaki** [BTAS/BTAS#80]
I noticed that when beta = 0.0, the current code scales the target area by 0.0, which is different from zero-ing out the area (because 0.0 * NaN = NaN). Is this the behavior that BLAS has? I thought that one can use uninitialized arrays for C with beta = 0.0.

**Comment by justusc** [comment]
I believe the netlib implementation of GEMM assigns zero to the C matrix when beta is equal to zero.

**Comment by shiozaki** [comment]
Thanks Justus, then this should be fixed. Also I noticed that the generic version is sometimes called even when the cblas calls are possible.

**Comment by evaleev** [comment]
DGEMV also
